<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Zend Framework Quickstart Application</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="/css/custom.css" rel="stylesheet">
</head>
<body>
<div class="container">

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">

                <a class="navbar-brand" href="/"> Тестовое задание</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?php echo $this->url(
                            ['controller' => 'section'],
                            'default',
                            true) ?>">Разделы</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <?php echo $this->layout()->content ?>

</div>


</body>
</html>
