<br/><br/>

<h1>Рубрики</h1>

<p><a class="btn btn-success" href="<?php echo $this->url(
        [
            'controller' => 'section',
            'action' => 'create'
        ],
        'default',
        true) ?>">Добавить рубрику</a></p>


<?php
if (count($this->entries) > 0) {
    ?>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($this->entries as $section) {
            ?>
            <tr>
                <td><?php echo $this->escape($section->id) ?></td>
                <td><?php echo $this->escape($section->name) ?></td>
            </tr>
            <?

        }
        ?>
        </tbody>
    </table>
    <?
}
?>